version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(composer dep)"
      prefix-development: "chore(composer dev dep)"
      include: "scope"
