language: php
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
php:
  - '7.3'
  - '7.4'
install:
  - composer install
script:
  - php app.php
