language: php
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
php:
  - '7.1'
  - '7.2'
  - '7.3'
cache:
  directories:
  - "~/.composer/cache"
install:
  - composer install
script:
  - php app.php
