name: Release
on: 
  push:
    tags-ignore: 
      - "**"
  pull_request:
    tags-ignore: 
      - "**"

jobs:
  test:
    name: Test @ PHP ${{ matrix.php-version }} - x86 - ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    strategy:
      matrix:
        php-version:
          - 7.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies::PHP${{ matrix.php-version }}
        run: |
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH
          composer update
      - name: Code Validation
        run: |
          php app.php
