name: Release
on: 
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "**"
    # Sequence of patterns matched against refs/tags
    tags-ignore: 
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore: 
      - "**"

jobs:
  test:
    name: Test @ PHP ${{ matrix.php-version }} - x86 - ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    strategy:
      matrix:
        php-version:
          - 7.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies::PHP${{ matrix.php-version }}
        run: |
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH
          composer update
      - name: Code Validation
        env:
          TESTS_USER_HEXONET: ${{ secrets.TESTS_USER_HEXONET }}
          TESTS_USERPASSWORD_HEXONET: ${{ secrets.TESTS_USERPASSWORD_HEXONET }}
          TESTS_USER_RRPPROXY: ${{ secrets.TESTS_USER_RRPPROXY }}
          TESTS_USERPASSWORD_RRPPROXY: ${{ secrets.TESTS_USERPASSWORD_RRPPROXY }}
        run: |
          php app_hexonet.php $TESTS_USER_HEXONET $TESTS_USERPASSWORD_HEXONET
          php app_cnr.php $TESTS_USER_RRPPROXY $TESTS_USERPASSWORD_RRPPROXY
        
